### ISSUE TITLE
Take Function  Input From user

### ISSUE THREAD

**Issue by AMANKANOJIYA** [AMANKANOJIYA/Numerical_Analysis#1]
Take **Function  Input**  From user And use the **user-provided function** in Two methods 
_1. Numerical_Analysis_
_2. Numerical_Integration_

**Comment by old-school-kid** [comment]
Use argparse to capture input from the user and use the same in any functions you want. These inputs can also be given from CLI

**Comment by AMANKANOJIYA** [comment]
Sir, if we use argparse, it will then be totally based on the command line, but then we have to customize it for use inside other projects @old-school-kid

**Comment by AMANKANOJIYA** [comment]
Sir, What I did is I am going to take function from the user as a string, and when we are going to do the operation, I am using eval to 
generate the function and to get the output on the return


![show](https://user-images.githubusercontent.com/50018596/122015541-d03c2080-cddd-11eb-89ab-63d93622e2b5.png)


@old-school-kid
